config/routes.rb
Rails.application.routes.draw do
  get "home/about" => 'homes#about'
  root :to => 'homes#top'
  resources :books , only: [:index, :create, :index, :show, :edit, :update, :destroy] do
   resource :favorites, only: [:create, :destroy]
   resources :book_comments, only: [:create, :destroy]
  end
  
  get '/search' => 'searchs#search'
  
  devise_for :users
  resources :users, only: [:index, :show, :edit, :update] do
   resource :relationship, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    has_many :favorites, dependent: :destroy
    
    def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
    end
    
    has_many :book_comments, dependent: :destroy
    
    validates :title, presence: true
    validates :body, presence: true,length: {maximum:200}
    
    def self.search_for(content, method)
    if method == 'perfect'
      Book.where(title: content)
    elsif method == 'forward'
      Book.where('title LIKE ?', content+'%')
    elsif method == 'backward'
      Book.where('title LIKE ?', '%'+content)
    else
      Book.where('title LIKE ?', '%'+content+'%')
    end
    end
  
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
    validates :comment, presence: true
    belongs_to :book
    belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  attachment :profile_image
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  validates :name, presence: true, length: {minimum: 2, maximum:20} ,uniqueness: true
  validates :introduction, length: {maximum:50}
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  # 自分がフォローされる側
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 自分がフォローする側
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # フォローする側の関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed
  
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end
  
  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
        user_path(resource)
  end
  
  def after_sign_up_path_for(resource)
        user_path(resource)
  end
  
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
    def create
        book = Book.find(params[:book_id])
        @book_comment = BookComment.new(book_comment_params)
        @book_comment.book_id = book.id
        @book_comment.user_id = current_user.id
        @book_comment.save
        redirect_to book_path(book.id)
    end
    
    def destroy
        @book = Book.find(params[:book_id])
        book_comment = @book.book_comments.find(params[:id])
		book_comment.destroy
		redirect_to request.referer
    end
    
    private
    def book_comment_params
    params.require(:book_comment).permit(:comment)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
      before_action :authenticate_user!
      
  def index
    # 共通部分のアクション
    @book = Book.new
    @User = User.find(current_user.id)
     # 
    @Books = Book.all
  end

  def show
    @book = Book.new
    @Book = Book.find(params[:id]) 
    @User = User.find(@Book.user_id)
    @book_comment= BookComment.new
  end
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if
     @book.save
     redirect_to book_path(@book.id)
     flash[:notice]="You have created book successfully."
    else
     @User = User.find(current_user.id)
     @Books = Book.all
     render :index
    end
  end

  def edit
    @book = Book.find(params[:id]) 
    if @book.user_id == current_user.id
     render :edit
    else
     redirect_to books_path
    end
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    redirect_to book_path(@book.id)
    flash[:notice]="You have updated book successfully."
    else
     render :edit
    end
  end
  
  def destroy
   book = Book.find(params[:id])
   book.destroy
   redirect_to books_path
  end
  
 private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    before_action :authenticate_user!
    
    def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to request.referer
    end
    
    def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def show
  end
  
  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    before_action :authenticate_user!
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end
  
  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end
  
  def followings
     user = User.find(params[:user_id])
     @Users = user.followings
  end

  def followers
     user = User.find(params[:user_id])
     @Users = user.followers
  end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
    before_action :authenticate_user!
    
    def search
    @model = params[:model]
    @content = params[:content]
    @method = params[:method]
     if @model == 'user'
        @records = User.search_for(@content, @method)
     else
        @records = Book.search_for(@content, @method)
     end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
  def index
    @book = Book.new
    @User = User.find(current_user.id)
    @Users = User.all
    @Books = @User.books
  end

  def show
    @book = Book.new
    @User = User.find(params[:id])
    @Users = User.all
    @Books = @User.books
  end


  def edit
    @User=User.find(params[:id])
    if @User == current_user
      render:edit
    else
      redirect_to user_path(current_user.id)
    end
  end
  
  def update
    @User = User.find(params[:id])
    if @User.update(user_params)
    redirect_to user_path(@User.id)
    flash[:notice]="You have updated user successfully."
    else
      render:edit
    end
  end
  
   private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<script src="https://kit.fontawesome.com/cdf8be78e7.js" crossorigin="anonymous"></script>
<div class="col-md-3">
                        <h2>User info</h2>
                        <table class="table">
                            <tbody>
                                <tr>
                                    <th><%= attachment_image_tag user, :profile_image , size: "100x100", fallback: "no_image.jpg" %></th>
                                </tr>
                                <tr>
                                    <th>name</th>
                                    <th><%=user.name%></th>
                                </tr>
                                <tr>
                                    <th>introduction</th>
                                    <th><%=user.introduction%></th>
                                </tr>
                                <tr>
                                    <th>follows</th>
                                    <th><%= link_to user.followings.count, user_followings_path(user) %></th>
                                </tr>
                                <tr>
                                    <th>followers</th>
                                    <th><%= link_to user.followers.count, user_followers_path(user) %></th>
                                </tr>
                            </tbody>
                        </table>
                        <div class="row">
                            <a><%= link_to "", edit_user_path(@User) , class:'btn btn-outline-secondary btn-block fas fa-user-cog'%></a>
                        </div>
                        <div class="row">
                        <% if current_user != user %>
                        <% if current_user.following?(user) %>
                        <%= link_to "フォロー外す", user_relationship_path(user.id), method: :delete, class: "btn btn-primary" %>
                        <% else %>
                        <%= link_to "フォローする", user_relationship_path(user.id), method: :post, class: "btn btn-success" %>
                        <% end %>
                        <% end %>
                        </div>
                        <h2>New book</h2>
                        <%= form_with model:book, local:true do |f| %>
                          <h4>Title</h4>
                          <%= f.text_field :title %>
                          <h4>Opinion</h4>
                          <%= f.text_area :body %>
                          <%= f.submit 'Create Book', class:'btn btn-success'%>
                        <% end %>
</div>

app/views/books/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-8 mx-auto">
            <!--バリデーションエラーメッセージ-->
            <div class="alert alert-danger">
            <% if @book.errors.any? %>
            <%= @book.errors.count %>error prohibited this obj from being saved:
            <% @book.errors.full_messages.each do |message| %>
            <%= message %>
            <% end %>
            <% end %>
            </div>
<!--投稿フォーム-->
<h1>Editing Book</h1>
 <%= form_with model:@book, local:true do |f| %>
<h4>Title</h4>
 <%= f.text_field :title %>
<h4>Opinion</h4>
 <%= f.text_area :body %>
 <div>
 <%= f.submit 'Update Book', class:'btn btn-success'%>
 </div>
 <%= link_to 'Show', book_path(@book.id) %> |
 <%= link_to 'Back', books_path %>
<% end %>
        </div>
    </div>
</div>

app/views/books/index.html.erb
<html>
    <body>
        <main>
            <% if @book.errors.any? %>
            <%= @book.errors.count %>error prohibited this obj from being saved:
            <% @book.errors.full_messages.each do |message| %>
            <%= message %>
            <% end %>
            <% end %>
            <div class="container px-5 px-sm-0">
                <div class="row">
                    <!--左側-->
                    <%= render 'books/list', user: @User, book: @book %>
                    <!--左側終-->
                    <div class="col-md-8 offset-md-1">
                        <h2>Books</h2>
                        <table class="table">
                            <thead>
                                <tr>
                                    <th></th><th>Title</th><th>Opinion</th><th>♡</th><th>コメント</th>
                                </tr>
                            </thead>
                            <tbody>
                                <% @Books.each do |book| %>
                                <tr>
                                    <td><%= link_to user_path(book.user.id) do %><%= attachment_image_tag book.user,:profile_image, size: "50x50" ,fallback: "no_image.jpg"%><% end %></td>
                                    <td><%= link_to book.title, book_path(book.id) %></td>
                                    <td><%= book.body %></td>
                                    
                                    <% if book.favorited_by?(current_user) %>
                                    <td><%= link_to book_favorites_path(book.id), method: :delete do %>♥<%= book.favorites.count %>いいね<% end %></td>
                                    <% else %>
                                    <td><%= link_to book_favorites_path(book.id), method: :post do %>♥<%= book.favorites.count %>いいね<% end %></td>
                                    <% end %>
                                    <td>コメント数：<%= book.book_comments.count %></td>
                                </tr>
                                <% end %>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </main>
    </body>
</html>

app/views/books/show.html.erb
<html>
    <body>
        <main>
            <div class="container px-5 px-sm-0">
                <div class="row">
                    <!--左側-->
                    <%= render 'books/list', user: @User, book: @book %>
                    <!--左側終-->
                    <div class="col-md-8 offset-md-1">
                        <h2>Book detail</h2>
                        <table class="table">
                            <tbody>
                                <tr>
                                    <td><%= link_to user_path(@Book.user.id) do %><%= attachment_image_tag @Book.user, :profile_image , size: "50x50" %></br><%=@Book.user.name %><%end %></td>
                                    <td><%= link_to @Book.title, book_path(@Book.id) %></td>
                                    <td><%= @Book.body %></td>
                                    <!--自分の投稿だった時に編集or削除-->
                                    <% if @Book.user.id == current_user.id %>
                                    <td><%= link_to "Edit", edit_book_path(@Book.id),class:'btn btn-success'%></td>
                                    <td><%= link_to "Destroy", book_path(@Book.id), method: :delete ,class:'btn btn-danger'%></td>
                                    <% end %>
                                    <!--いいね機能-->
                                    <% if @Book.favorited_by?(current_user) %>
                                    <td><%= link_to book_favorites_path(@Book.id), method: :delete do %>♥<%= @Book.favorites.count %>いいね<% end %></td>
                                    <% else %>
                                    <td><%= link_to book_favorites_path(@Book.id), method: :post do %>♥<%= @Book.favorites.count %>いいね<% end %></td>
                                    <% end %>
                                    <!--コメント数-->
                                    <td>コメント数：　<%= @Book.book_comments.count %></td>
                                </tr>
                                    
                                <% @Book.book_comments.each do |book_comment| %>
                                <% book_comment_user = book_comment.user %>
                                <tr>
                                    <td>
                                        <%= link_to user_path(book_comment_user), class: "user_#{book_comment_user.id}" do %>
                                        <%= attachment_image_tag book_comment_user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: "50x50" %><br>
                                        <%= book_comment_user.name %>
                                        <% end %>
                                    </td>
                                    <td>
                                        <%= book_comment.comment %>
                                    </td>
                                    <% if current_user == book_comment_user %>
                                    <td>
                                        <%= link_to 'Destroy', book_book_comment_path(book_comment.book_id, book_comment.id), class: 'btn-sm btn-danger', method: :delete %>
                                    </td>
                                    <% end %>
                                </tr>
                                <% end %>
                            </tbody>
                        </table>
                        <!--コメント送信用-->
                        <div>
                            <%= form_with model:[@Book, @book_comment],local: true do |f| %>
                            <%= f.text_area :comment %> </br>
                            <%= f.submit "送信"%>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </body>
</html>

app/views/homes/about.html.erb
<body>
    <main>
        <p id="notice"></p>
        <div class="container">
            <div class="row">
                <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
            </div>
        </div>
    </main>
</body>

app/views/homes/top.html.erb
<html>
    <body>
        <main>
            <div class="container">
                 <div class="row">
                     <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
                               <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
                               <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
                               <p>you can share and exchange  your opinions , inpressions , and emotions</p>
                               <p> about various books!</p>
            <div class="btn-wrapper col-10 mx-auto">
                <div class="row">
                    <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
                </div>
                <div class="row">
                    <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>
                </div>
            </div>
                     </div>
                 </div>
            </div>
        </main>
    </body>
</html>

app/views/relationships/followers.html.erb
<h2>Follower Users</h2>
<% if @Users.exists? %>
  <%= render '/users/index', users: @Users %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/followings.html.erb
<h2>Follow Users</h2>
<% if @Users.exists? %>
  <%= render '/users/index', users: @Users %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/searchs/search.html.erb
<% if @model == 'user'%>
 <h3>Users serch for "<%= @content %>"</h3>
 <%= render 'users/index', users: @records %>
<% elsif @model =='book'%>
<h3>Users serch for "<%= @content %>"</h3>
<table class="table">
 <thead>
  <tr>
   <th></th><th>Title</th><th>Opinion</th>
  </tr>
 </thead>
 <tbody>
  <% @records.each do |book| %>
  <tr>
   <td><%= link_to user_path(book.user.id) do %><%= attachment_image_tag book.user,:profile_image, size: "50x50" ,fallback: "no_image.jpg"%><% end %></td>
   <td><%= link_to book.title, book_path(book.id) %></td>
   <td><%= book.body %></td>
  </tr>
  <% end %>
  </tbody>
 </table>
<% end %>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg",size: '50x50' ) %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td>
          <% if current_user != user %>
            <% if current_user.following?(user) %>
              <%= link_to "フォロー外す", user_relationship_path(user.id), method: :delete %>
            <% else %>
              <%= link_to "フォローする", user_relationship_path(user.id), method: :post %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <!--バリデーションエラーメッセージ-->
　　　　<% if @User.errors.any? %>
　　　　<%= @User.errors.count %>error prohibited this obj from being saved:
　　　　<% @User.errors.full_messages.each do |message| %>
　　　　<%= message %>
　　　　<% end %>
　　　　<% end %>
<!--投稿フォーム-->
<h2>User info</h2>
<%= form_with model:@User, local:true do |f| %>
  <h4>Name</h4>
  <%= f.text_field :name %>
  <h4>Image</h4>
  <%=  f.attachment_field :profile_image %>
  <h4>Introduction</h4>
  <%= f.text_area :introduction %></br>
  <%= f.submit 'Update User', class:'btn btn-success' %>
<% end %>
</div>
</div>
</div>

app/views/users/index.html.erb
<html>
    <body>
        <main>
            <div class="container px-5 px-sm-0">
                <div class="row">
                    <!--左側-->
                    <%= render 'books/list', user: @User, book: @book %>
                    <!--左側終-->
                    <div class="col-md-8 offset-md-1">
                        <h2>Users</h2>
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>image</th><th>name</th><th></th>
                                </tr>
                            </thead>
                            <tbody>
                                <% @Users.each do |user| %>
                                <tr>
                                    <td><%= link_to user_path(user.id) do %><%= attachment_image_tag user, :profile_image , size: "50x50" , fallback: "no_image.jpg" %><% end %></td>
                                    <td><%= user.name %></td>
                                    <td>フォロー数：<%= user.followings.count %></td>
                                    <td>フォロワー数： <%= user.followers.count %></td>
                                    <td>
                                        <% if current_user != user %>
                                        <% if current_user.following?(user) %>
                                        <%= link_to "フォローを外す", user_relationship_path(user.id) , method: :delete %>
                                        <% else %>
                                        <%= link_to "フォローする", user_relationship_path(user.id) , method: :post %>
                                        <% end %>
                                        <% end %>
                                    </td>
                                    <td><%= link_to "Show", user_path(user.id) %></td>
                                    <% end %>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </main>
    </body>
</html>

app/views/users/show.html.erb
<html>
    <body>
        <main>
            <div class="container px-5 px-sm-0">
                <div class="row">
                    <!--左側-->
                    <%= render 'books/list', user: @User, book: @book %>
                    <!--左側終-->
                    <div class="col-md-8 offset-md-1">
                        <h2>Books</h2>
                        <table class="table">
                            <thead>
                                <tr>
                                    <th></th><th>Title</th><th>Opinion</th>
                                </tr>
                            </thead>
                            <tbody>
                                <% @Books.each do |book| %>
                                <tr>
                                    <td><%= link_to user_path(@User) do %><%= attachment_image_tag @User, :profile_image , size: "50x50" %><% end %></td>
                                    <td><%= link_to book.title, book_path(book.id) %></td>
                                    <td><%= book.body %></td>
                                    <td>コメント数：　<%= book.book_comments.count %></td>
                                </tr>
                                <% end %>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </main>
    </body>
</html>