config/routes.rb
Rails.application.routes.draw do
  get "home/about" => 'homes#about'
  root :to => 'homes#top'
  resources :books , only: [:index, :create, :index, :show, :edit, :update, :destroy] do
   resource :favorites, only: [:create, :destroy]
   resources :book_comments, only: [:create, :destroy]
  end
  
  get '/search' => 'searchs#search'
  
  devise_for :users
  resources :users, only: [:index, :show, :edit, :update] do
   resource :relationship, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    has_many :favorites, dependent: :destroy
    
    def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
    end
    
    has_many :book_comments, dependent: :destroy
    
    validates :title, presence: true
    validates :body, presence: true,length: {maximum:200}
    
    def self.search_for(content, method)
    if method == 'perfect'
      Book.where(title: content)
    elsif method == 'forward'
      Book.where('title LIKE ?', content+'%')
    elsif method == 'backward'
      Book.where('title LIKE ?', '%'+content)
    else
      Book.where('title LIKE ?', '%'+content+'%')
    end
    end
  
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
    validates :comment, presence: true
    belongs_to :book
    belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  attachment :profile_image
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  validates :name, presence: true, length: {minimum: 2, maximum:20} ,uniqueness: true
  validates :introduction, length: {maximum:50}
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  # 自分がフォローされる側
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 自分がフォローする側
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # フォローする側の関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed
  
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end
  
  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
        user_path(resource)
  end
  
  def after_sign_up_path_for(resource)
        user_path(resource)
  end
  
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
      before_action :authenticate_user!
      
  def index
    # 共通部分のアクション
    @book = Book.new
    @User = User.find(current_user.id)
     # 
    @Books = Book.all
  end

  def show
    @book = Book.new
    @Book = Book.find(params[:id]) 
    @User = User.find(@Book.user_id)
    @book_comment= BookComment.new
  end
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if
     @book.save
     redirect_to book_path(@book.id)
     flash[:notice]="You have created book successfully."
    else
     @User = User.find(current_user.id)
     @Books = Book.all
     render :index
    end
  end

  def edit
    @book = Book.find(params[:id]) 
    if @book.user_id == current_user.id
     render :edit
    else
     redirect_to books_path
    end
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    redirect_to book_path(@book.id)
    flash[:notice]="You have updated book successfully."
    else
     render :edit
    end
  end
  
  def destroy
   book = Book.find(params[:id])
   book.destroy
   redirect_to books_path
  end
  
 private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    before_action :authenticate_user!
    
    def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to request.referer
    end
    
    def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def show
  end
  
  def about
  end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
    before_action :authenticate_user!
    
    def search
    @model = params[:model]
    @content = params[:content]
    @method = params[:method]
     if @model == 'user'
        @records = User.search_for(@content, @method)
     else
        @records = Book.search_for(@content, @method)
     end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
  def index
    @book = Book.new
    @User = User.find(current_user.id)
    @Users = User.all
    @Books = @User.books
  end

  def show
    @book = Book.new
    @User = User.find(params[:id])
    @Users = User.all
    @Books = @User.books
  end


  def edit
    @User=User.find(params[:id])
    if @User == current_user
      render:edit
    else
      redirect_to user_path(current_user.id)
    end
  end
  
  def update
    @User = User.find(params[:id])
    if @User.update(user_params)
    redirect_to user_path(@User.id)
    flash[:notice]="You have updated user successfully."
    else
      render:edit
    end
  end
  
   private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_search.html.erb
<%= form_with url: search_path, method: :get , local: true do |f| %>
 <%= f.text_field :content %>
 
 <!--①プルダウンの選択肢を作成する-->
 <!--%= f.select :保存先のカラム名, [["選択肢１", "実際にDBに保存させる内容"], ["選択肢２", "実際にDBに保存させる内容"]], include_blank: "選択して下さい" %>-->
 
 <!--※プルダウンの選択肢をDB内のあるテーブルの特定のカラムの内容にすること-->
 <!--%= f.collection_select :保存先のカラム名, テーブル（モデル）名.all, :実際にDBに保存させるカラム名, :選択肢に用いるカラム名, include_blank: "選択して下さい" %>-->
 
 <!--({"完全一致"=>"perfect","前方一致"=>"forward"...の記述で、
"選択肢で表示する文字"=>DBに渡す値（保存させる内容）となっています。-->
 <%= f.select :model, options_for_select({ "User" => "user" , "Book" => "book" } ) %>
 <%= f.select :method, options_for_select({"完全一致" => "perfect", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partial" }) %>
 <%= f.submit '検索' %>
 <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/cdf8be78e7.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          
            <% if user_signed_in? %>
          <li class=nav-link>
            <%= link_to "Home", user_path(current_user) , class:'nav-link text-light fas fa-home'%>
          </li>
          <li class=nav-link>
            <%= link_to "Users", users_path ,class:'nav-link text-light fas fa-users'%>
          </li>
          <li class=nav-link>
            <%= link_to "Books", books_path ,class:'nav-link text-light fas fa-book-open'%>
          </li>
          <li class="nav-link">
            <%= link_to "logout", destroy_user_session_path, method: :delete ,class:'nav-link text-light fas fa-sign-out-alt' %>
            </li>
            <% else %>
          <li class=nav-link>
             <%= link_to "Home", root_path ,class:'nav-link text-light fas fa-home'%>
          </li>
          <li class=nav-link>
            <!--link-->
            <%= link_to "About", home_about_path ,class:'nav-link text-light fas fa-link'%>
          </li>
          
          <li class=nav-link>
            <%= link_to "sign up", new_user_registration_path ,class:'nav-link text-light fas fa-user-plus'%>
          </li>
          
          <li class="nav-link">
            <%= link_to "login", new_user_session_path,class:'nav-link text-light fas fa-sign-in-alt'%>
          </li>
            <% end %>
        </ul>
      </div>
    </div>
    </nav>
    
  </header>
   <main>
    <div class="container">
      <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-8">
     <% if user_signed_in? %>
     <%= render 'layouts/search' %>
     <% end %>
        </div>
      </div>
    </div>
    
      <% if flash[:notice] %>
  　<div>
    　<%= flash[:notice] %>
  　</div>
  　<% end %>
  　</main>
  <%= yield %>

  </body>
  <!--footer-->
  <footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto"><p>CopyRight Infratop.inc</p></div>
    </div>
  </div>
  </footer>
</html>